### ISSUE TITLE
1.1 画面遷移を学習する

### ISSUE THREAD

**Issue by kentoapps** [kentoapps/TakaProject#1]
# 学習内容
- Activityを作成し表示する
- ActivityからActivityの画面遷移をする
- 各Viewを使う（TextView, Button, ImageView）

# 要件
- MainActivityにテキストとボタンを配置すること
- MainActivityのボタンを押下するとDetailActivityに遷移すること
- DetailActivityには画像とタイトルのテキストと説明のテキストを配置すること

# 特記事項
- 文字や画像のサイズ、位置などはだいたいでいいです
- DetailActivityは自分で作成してください
- 画像はプロジェクト内`app/src/main/res/drawable/logo.png`にあります
- 説明テキストは以下を使用してください  
```
空条承太郎がエジプトでの決戦でDIOを撃破してから10年以上の月日が流れた、1999年。日本のM県S市にある杜王町（もりおうちょう）に住む高校生広瀬康一の視点と語りで物語が語られる。
海洋冒険家となった承太郎は、老いて死を実感するようになった祖父のジョセフ・ジョースターの遺産分配について調査した結果、彼の隠し子である東方仗助（ひがしかた じょうすけ、ジョジョ）が杜王町に住んでいることを知る。仗助と話をするために杜王町を訪ねた承太郎は、偶然、不良学生に絡まれていた仗助を発見する。
```

# 画面構成
MainActivity.java|DetailActivity.java
---|---
![mainactivity](https://cloud.githubusercontent.com/assets/8979200/21521293/03ff2786-cd3f-11e6-9929-67a517176d68.png)|![detailactivity](https://cloud.githubusercontent.com/assets/8979200/21521296/0bece9d8-cd3f-11e6-85ac-28a7ae7527d0.png)

**Comment by haru-taka** [comment]
chapter3まで
chapter8(画面遷移)

**Comment by kentoapps** [comment]
完璧です！
